apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: organizer-secrets
spec:
  encryptedData:
{{ toYaml .Values.sealedSecrets.encryptedData | indent 4 }}
  template:
    metadata:
      name: organizer-secrets
