url: app2.localhost
title: cipciusia
wpMail: cipciusia@test.com
dbUser: pussy
dbPassword: pussy
dbRootPassword: rootpussy
wpUser: pussycat
wpPassword: pussycat
sftpUser: pusstp
sftpPassword: pusstp
sftpPort: 30022
