env: "staging"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: staging.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 80

deployments:
  - name: web-server
    image: ghcr.io/b-zago/portfolio/server:latest
    imagePullSecret: ghcr-creds
    runsOn: nginx
    component: server
    containerPort: 80
