apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: localstack-auth
spec:
  encryptedData:
    token: AgBBA/+tk1R/Mr58Py/dZxHKS1h++x5mpLICh2cEK7nxlMrWaum5vzEx+nTsTowmjwthLHBXTC/v7vV94mUf7YQ5J11hCG+In941+F7UCNmf1mOGTpH1Evq0fJ2eKd2BpDrNeiWyuixPyrDRFv9LHva+FmfTbta8DiGH/p5rCdLPODOyRwR52QQuzeUG2Z/DmQjNS1Vpl9H5t1RfmfrevTN7e7w4NSAVfUhoSKbpxDUUKosPeDdLQstjpCPvazCV4lwOtU5vbFmDc0E962TFOFaIzAXahq4DvXaPxw5kUGXpY/Y5LdX5wAP0VZ+90vyUb0AY0UlAg3gmX+85w+AinFDEH0QgdU3+6KzPHThfV8nAnsL+qdvOhI2I9ODdgJ3S3DJzSg8v1iTRIEP15wLBZJnLE91nmb56xCR/XSpEP3alItetCNewkWrjgm1AZD81oNaPpiLVNAp8LYAZcJbvUEFS7SkrqQGZq6Jhmjc3jeG3ptEXC+fxa7l0+mLu9Y1JzZddAY9y/zcfiygcWpcD5lbsqdhQti3j3NXTN1qL8ui4yqRijSNDNO0w+q6zoJJmO8sp/1W/hDO/gMLV6zCKuXBl/xZkIMegLQiVTva+wLi6RxWEhI/e0Ss4YhSc95N5AdeuqyrvohAc98O5c23KqJeZ3hGBn0Y9fv2nogWATowfFf/HT+/WHMkEW9gZhMxiA5wOL+0SXgVYQ/VYIGW4ZnEZmJU7JN+8cwT6dqfpJ/BTu4nQQeG1HT4=
  template:
    metadata:
      name: localstack-auth
    type: Opaque
