apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBEm7gYmBWkXMzxOxXqwSwdkwO6lOGlHfx3fH7fDuiYs5cO+rtKiEfG6q3hkKDkcDnXeWJA8SMyGhMv0q+gkzUFyfy2eScSWXEOQUVQGqbBMVSHdaL6ZnRr9OzPh4RWbA4HztNqNjUGXGbU0vE3gZNca/pqZ5vuWq12meJXiyIh0w7sAAE+xt04yj6o1Hx0THowmp77scMmMNTW2qBBHQMJtLdijRvyR6tWlXuu0f0FSMUijVs22xHr50WNvojzqDXDRewEdyyBgfchEF8M1i7QEae+IHEi09UZVL7a9Cmb86e9DJUd/cQjytE9/O9yMyCObhI8yVE8yvwgHvt15onKUNp5hZewx8rXXywcWPkOotNUyl6JM6ompEZ2rWUbdvW1jIohMbxQTqlSaN0vZcTCM55wLAiVLIgcPw8vb89fGd0UIFt2KPl3sDlVFcbnIZxOc5b550oBcANw30W9lZG4vWqjH5V7vPxblrG9fPfVk3fGv1/akP2A8N8SNyQsuA8o8fEgF96UTmhDaPMJovX8U2IWQSIzF5kQTxcuWdsd1Mm0ehGPpQepnc3kha6Srg03LTzhBMzMiHpUFbUBNz/+YR4Ic15h6DJBqxw6Z21VQ4XBBFtzQzZL9X6npyvyS6clYyyu+DdwwghbXJSgclt+hAE8m/ed9Jx1XNBYgeVxqTNb6DqtsK7hINzYkKiFlAYSWtDOKENtzVCz7HhpvbYQMYTjM/aFjgOdnGl8ct6PL54DMUIM+gu7Iq80hIbWCduK+ZCCJS+YRy8mjbtmPhQ4qGgIR1IAfSde/ZMs6eAFXf9vhU+5saOjGsJtuyxKj/BaSQDp/NKtheDzGUWvPUzkDUJ/aQs4YZvE8HwLhHZwx8l6ccKjdlg6JF6j0ApcSKvG6uP84PS3MjTxfS+c2N91gh0lsnwDgrKFMY8=
  template:
    metadata:
      name: ghcr-creds
      namespace: staging
    type: kubernetes.io/dockerconfigjson
