apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgBIEndFw27yK2FJDO4PbG47vAzEurEM1+LE5mgtLXTDYXiOgFvMdLTJ8y1twbG7xodvFmySZtOrT6OqR9mgGyY1dHhGVbG0/2lJtF4XmoVFPILCtpd8voFFXdvfH8SBV/PROtzRcZD1Iq/nxqpdeHDWu6KGC7ZSfPlDiIbpj5HtzIgNqVI4uJz/S7a3MqWy57jP84jR0qitw5XjmAux3kiG8qi3Gl0iTm64JBYLGmcRMJtj3SBwp2Y+MVrFxOHdhB8DJlYjh9Zwfq/ZNyefxtR/q14R8jDjOD/SUteK9ZW5+54MrIKn2BBN7N/PUK39bhwaNFktsho36hKLXsKU4dASZGSE+hjb29eUw1iS9q47XKDrcHb7O2087cG+ectoWdP6FJQ4Ao4VeIhZkn8l8gS/JmRTTty3xye9zAR1shcypUjra8X9f6tP20EbtY0MAtK4O1Gpagod8f27R08soyuG4/kwg/On4R7gM0MfxxUC+LTSy3u8v562/hvjgDIkOn2RoLihjPZDxedkkxIoQePCvxGatiLNnigvSP58zs7Vft9+NN8YO/U/QpXBpo9BowCGGdXHQZ+4ixiPo3suuTlEXy01H/4BZAgqUjE4t0mtQ+seSOgvJ9m3KEtZNR8GZpXQ1dXc/LVyPddIz9fIvm/mSisS7vPK8SZ1h2d9xi0C13JqnKKgxbTcJ2BOuWQoUc4NXsoaHvO0g+ig8v1CHd4fz2EBdc+dTE85LWYnPZZIetxTcLr8dmrF6Z+0uwz2zSwMGft8WATjO+AdMGfy6xil+mfL28yEDvC3LbNz+iEzIirzrnT4Y57PnoDO9VysYGjgWXnc5zLM4tWQtRD8XGuUgVpV7fhWDGRsAm7rzz0t9vOQcOfZW2FDdTipX6P2XKhgBFeOQjGznKz0Zs8r6rbe1TAjgucBqqomlB4=
  template:
    metadata:
      name: ghcr-creds
      namespace: prod
    type: kubernetes.io/dockerconfigjson
